# Generated by Django 5.1.3 on 2024-12-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='deadline',
            field=models.DateTimeField(verbose_name='Uyga vazifa muddati'),
        ),
    ]
