# Generated by Django 5.1.3 on 2024-12-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_lessons_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='homework',
            field=models.TextField(verbose_name='Uyga vazifa'),
        ),
    ]
