# Generated by Django 5.1.3 on 2024-12-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_lessons_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nomi'),
        ),
    ]
