# Generated by Django 5.1.3 on 2024-12-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('description', models.TextField(default="Ma'lumot qo'shilmadi.", verbose_name='Tavsifi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('published', models.BooleanField(default=False, verbose_name='Nashr etilgan')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.types')),
            ],
        ),
    ]
