# Generated by Django 5.1.3 on 2024-12-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'ordering': ['-id'], 'verbose_name': 'Gullar ', 'verbose_name_plural': 'Gullar'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'ordering': ['-id'], 'verbose_name': 'Turlar ', 'verbose_name_plural': 'Turlar'},
        ),
        migrations.AddField(
            model_name='flowers',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Soni'),
        ),
    ]
